### ISSUE TITLE
"window is not defined" error in webworkers

### ISSUE THREAD

**Issue by d07RiV** [ClickSimply/cpp-wasm-loader#10]
Trying to import a module in a web worker results in `window is not defined` error.

It is used in this line of minimal env:

		var globalEnv = {
			"global": window,
			"env": {

What's the purpose of it? As far as I can tell, nothing actually uses `global` env. But just in case, I replaced it with `self` if window is not defined.

PR: https://github.com/ClickSimply/cpp-wasm-loader/pull/11

**Comment by only-cliches** [comment]
PR has been accepted, I'll push a new release to NPM with those changes soon.

**Comment by only-cliches** [comment]
The PR is live as of `0.9.0`.
