### ISSUE TITLE
Memory manager writes over globals

### ISSUE THREAD

**Issue by d07RiV** [ClickSimply/cpp-wasm-loader#12]
Memory allocation starts at address 0, which eventually writes over constants and other global data.

**Comment by only-cliches** [comment]
I haven't ran into this issue in my apps, I can think of a few solutions but not sure where/how you're running into this...

If the memory is setup when the wasm is initialized you can simply run `.scan()` on the memory class to have it read the memory and mark the occupied space.

The only other thing that comes to mind is setting some kind of initialization option allowing you to set the first X bytes of the memory as occupied.  Maybe a new method on the memory class like `.mark(bytes: number)`.

Let me know what you think.

**Comment by d07RiV** [comment]
I think the correct approach would be parsing static data and stack size from emscripten output (values like STACK_TOP and STATICTOP). With the current memory implementation, even string literals will get overwritten.

Scan is unreliable because a program could use a static array but not initialize any values at startup.

**Comment by only-cliches** [comment]
This issue has been resolved in `0.9.0`, just pushed to NPM.

The memory manager class uses `STATICTOP` to mark off the beginning of memory as occupied so it won't be overwritten by future memory requests.
