### ISSUE TITLE
Getting error when using the provided example in "WebAssembly.instantiate()"

### ISSUE THREAD

**Issue by sudhanshug16** [ClickSimply/cpp-wasm-loader#15]
I tried to plug the example in my project but got the following error:
![image](https://user-images.githubusercontent.com/9914480/69188334-54ff8380-0b42-11ea-8f63-20e3c80df652.png)

my c file:
```
#include <emscripten.h>

extern "C"
{
	EMSCRIPTEN_KEEPALIVE
	float add(float a, float b) {
		return a + b;
	}
	
}
```

my js file: 
```
wasm.init().then(function(mod) {
    console.log(mod.exports.add(2, 3));
});
```

**Comment by ScarboroughCoral** [comment]
I got the same error,too.

**Comment by ScarboroughCoral** [comment]
> I tried to plug the example in my project but got the following error:
> ![image](https://user-images.githubusercontent.com/9914480/69188334-54ff8380-0b42-11ea-8f63-20e3c80df652.png)
> 
> my c file:
> 
> ```
> #include <emscripten.h>
> 
> extern "C"
> {
> 	EMSCRIPTEN_KEEPALIVE
> 	float add(float a, float b) {
> 		return a + b;
> 	}
> 	
> }
> ```
> 
> my js file:
> 
> ```
> wasm.init().then(function(mod) {
>     console.log(mod.exports.add(2, 3));
> });
> ```

Did you solve the problem?help!! 😄

**Comment by sudhanshug16** [comment]
No. Actually i couldn't solve the problem

**Comment by mskorokhodov** [comment]
Hey, found a way to fix it, just run your webpack with -p flag, have no idea why but it works...

**Comment by mariorodriguespt** [comment]
@mskorokhodov I confirm your fix works.
